name: Build webpage

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["master"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  id-token: write

jobs:
  # Single deploy job since we're just deploying
  build:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Tempura
        uses: baptiste0928/cargo-install@v1.3.0
        with:
          crate: tempura
      - name: Build
        run: tempura build
      - name: Prepare for new branch
        run: rm .gitignore
      - name: New branch
        uses: EndBug/add-and-commit@v9
        with:
          new_branch: release
